#pragma config(Motor,  port3,           dr1,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           ch1,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           drt2,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           ch2,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           dr2,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           drt1,          tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void lift(int speed){
	motor[dr1] = speed;
	motor[dr2] = -speed;
	motor[drt1] = -speed;
	motor[drt2] = speed;
}

void chainbar(int speed){
	motor[ch1] = speed;
	motor[ch2] = -speed;
}

task main()
{
	while(true){


		if(vexRT[Btn5U] == 1){
			chainbar(100);
			}else if(vexRT[Btn5D] == 1){
			chainbar(-100);
			}else{
			chainbar(15);
		}

		if(vexRT[Btn6U])
		{
			lift(100);
		}else if(vexRT[Btn6D])
		{
			lift(-100);
			}else{
			lift(15);
		}
	}


}
