#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           Claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RF,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           RB,            tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port4,           Arm,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           Arm2,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           MLift2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           MLift,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LF,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           LB,            tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//!!Code automatically generated by 'ROBOTC' configuration wizard               !!//
//!!Code automatically generated by 'ROBOTC' configuration wizard               !!//

//motor speed for mobile lift
int Lift = 120;
//motor speed for Arm
int RoArm = 85;
//motor speed for claw
int RoClaw = 120;

task main()
{

 while (true){

//============= MAIN CONTROLER =================

        //code for chassis
        motor[LF] = vexRT[Ch2];
        motor[LB] = vexRT[Ch2];
        motor[RF] = vexRT[Ch3];
        motor[RB] = vexRT[Ch3];

        //code for mobile lift
        if (vexRT[Btn5D])
        {
          motor[MLift] = -Lift/1.4;
          motor[MLift2] = -Lift/1.4;
        }
        else if (vexRT[Btn5U])
        {
          motor[MLift] = Lift;
          motor[MLift2] = Lift;
        }
        else
        {
          motor[MLift] = 0;
          motor[MLift2] = 0;
        }
//============= PARTNER CONTROLER ==============

        //code for arm
        if (vexRT[Btn5UXmtr2])
        {
            motor[Arm] = RoArm;
            motor[Arm2] = RoArm;
        }
        else if (vexRT[Btn6UXmtr2])
        {
            motor[Arm] = -RoArm/1.4;
            motor[Arm2] = -RoArm/1.4;
        }
        else
        {
            motor[Arm] = 0;
            motor[Arm2] = 0;
        }

        //code for claw

        if (vexRT[Btn8RXmtr2])
        {
            motor[Claw] = RoClaw;
        }
        else if (vexRT[Btn8DXmtr2])
        {
            motor[Claw] = -RoClaw;
        }
        else
        {
            motor[Claw] = 0;
        }

    }
}
