#pragma config(Sensor, in5,    C_POT,          sensorPotentiometer)
#pragma config(Sensor, in4,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl7,  LIFTE,           sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  RIGHT_DRIVE_ENC, sensorQuadEncoder)
#pragma config(Sensor, dgtl11, LEFT_DRIVE_ENC, sensorQuadEncoder)
#pragma config(Motor,  port1,           MOBILE_GOAL_INTAKE, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port3,           Chainbar,      tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           RIGHT_DRIVE_F, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           RIGHT_DRIVE_B, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           RIGHT_LIFT_BOTTOM, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port2,           LEFT_LIFT_BOTTOM, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           LEFT_DRIVE_B,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           LEFT_DRIVE_F,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           LIFT,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          ROLLERS,       tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "simpleSensors.h"

void _lift(int speed){
	//motor[LEFT_LIFT_TOP] = speed;
	motor[LEFT_LIFT_BOTTOM] = speed;
	motor[RIGHT_LIFT_BOTTOM] = speed;
	//motor[RIGHT_LIFT_TOP] = speed;
	motor[LIFT] = speed;
}
void lift_Up(int height, int speed){
	int L_error = height - LIFT_ENC;
	while(L_error > 0){
		_lift(speed);
		L_error = height - LIFT_ENC;
	}
	_lift(-15);
	wait1Msec(100);
	_lift(0);
}

void lift_Down(int height, int speed){
	int L_error = height - LIFT_ENC;
	while(L_error < 0){
		_lift(-speed);
		L_error = height - LIFT_ENC;
	}
	_lift(15);
	wait1Msec(100);
	_lift(0);
}
void _liftClr(){
	LIFT_ENC = 0;
}
void _rollers(int speed){
	motor[ROLLERS] = speed;
}


void _chainbar(int speed){
	motor[Chainbar] = speed;
}

void chainbar_down(int speed){
	int C_error = f_Pot - 20;
	clearTimer(T1);
	while(C_error > 0 && time1(T1) < 1000){
		_chainbar(speed);
		C_error = f_Pot - 20;
	}
	_chainbar(0);
}

void chainbar_up(int time, int speed){
 _chainbar(-speed);
 wait1Msec(time);
	}


void _intake(int speed){
	motor[ROLLERS] = -speed;
}
