#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  imeL,           sensorNone)
#pragma config(Sensor, dgtl2,  imeR,           sensorNone)
#pragma config(Sensor, I2C_1,  RBEn,           sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  LBEn,           sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           Claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RF,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RB,            tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port4,           Arm,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Arm2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           MLift2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           MLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LF,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LB,            tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//!!Code automatically generated by 'ROBOTC' configuration wizard               !!//
//!!Code automatically generated by 'ROBOTC' configuration wizard               !!//

//motor speed for mobile lift
int R_Freq = 150;
int Lift = 127;
//motor speed for Arm
int RoArm = 80;
//motor speed for claw
int RoClaw = 120;
int R_Batt = 7919;
int P_Freq = R_Freq * (R_Batt / nImmediateBatteryLevel);
// Initial values for Sensors:
// Initial values for IMEs: port 3 = 0  port 9 = 0

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{

		wait1Msec( P_Freq * 1 );		// wait 150

		// 150  Sensors: no change  IMEs: no change
		motor[ port1 ] = 120;
		motor[ port2 ] = 99;
		motor[ port3 ] = 99;
		motor[ port8 ] = 46;
		motor[ port9 ] = 46;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 300  Sensors: no change  IMEs: no change
		motor[ port2 ] = 96;
		motor[ port3 ] = 96;
		wait1Msec( P_Freq * 2 );		// wait 300

		// 600  Sensors: no change  IMEs: no change
		motor[ port2 ] = 37;
		motor[ port3 ] = 37;
		motor[ port4 ] = -120;
		motor[ port5 ] = -120;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 750  Sensors: no change  IMEs: no change
		motor[ port2 ] = 1;
		motor[ port3 ] = 1;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 900  Sensors: no change  IMEs: no change
		motor[ port2 ] = -5;
		motor[ port3 ] = -5;
		motor[ port8 ] = 1;
		motor[ port9 ] = 1;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 1050  Sensors: no change  IMEs: no change
		motor[ port4 ] = 0;
		motor[ port5 ] = 0;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 1200  Sensors: no change  IMEs: no change
		motor[ port8 ] = 6;
		motor[ port9 ] = 6;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 1350  Sensors: no change  IMEs: no change
		motor[ port8 ] = 1;
		motor[ port9 ] = 1;
		wait1Msec( P_Freq * 2 );		// wait 300

		// 1650  Sensors: no change  IMEs: no change
		motor[ port6 ] = 127;
		motor[ port7 ] = 127;
		motor[ port8 ] = 6;
		motor[ port9 ] = 6;
		wait1Msec( P_Freq * 2 );		// wait 300

		// 1950  Sensors: no change  IMEs: no change
		motor[ port8 ] = 1;
		motor[ port9 ] = 1;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 2100  Sensors: no change  IMEs: no change
		motor[ port6 ] = 0;
		motor[ port7 ] = 0;
		motor[ port8 ] = 6;
		motor[ port9 ] = 6;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 2250  Sensors: no change  IMEs: no change
		motor[ port8 ] = 1;
		motor[ port9 ] = 1;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 2400  Sensors: no change  IMEs: no change
		motor[ port2 ] = 7;
		motor[ port3 ] = 7;
		motor[ port8 ] = 22;
		motor[ port9 ] = 22;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 2550  Sensors: no change  IMEs: no change
		motor[ port2 ] = 17;
		motor[ port3 ] = 17;
		motor[ port8 ] = 62;
		motor[ port9 ] = 62;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 2700  Sensors: no change  IMEs: no change
		motor[ port2 ] = 92;
		motor[ port3 ] = 92;
		motor[ port8 ] = 72;
		motor[ port9 ] = 72;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 2850  Sensors: no change  IMEs: no change
		motor[ port2 ] = 118;
		motor[ port3 ] = 118;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 3000  Sensors: no change  IMEs: no change
		motor[ port8 ] = 75;
		motor[ port9 ] = 75;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 3150  Sensors: no change  IMEs: no change
		motor[ port2 ] = 127;
		motor[ port3 ] = 127;
		motor[ port8 ] = 80;
		motor[ port9 ] = 80;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 3300  Sensors: no change  IMEs: no change
		motor[ port8 ] = 88;
		motor[ port9 ] = 88;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 3450  Sensors: no change  IMEs: no change
		motor[ port2 ] = 92;
		motor[ port3 ] = 92;
		motor[ port8 ] = 1;
		motor[ port9 ] = 1;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 3600  Sensors: no change  IMEs: no change
		motor[ port2 ] = 1;
		motor[ port3 ] = 1;
		motor[ port6 ] = -127;
		motor[ port7 ] = -127;
		wait1Msec( P_Freq * 5 );		// wait 750

		// 4350  Sensors: no change  IMEs: no change
		motor[ port2 ] = -13;
		motor[ port3 ] = -13;
		motor[ port8 ] = -31;
		motor[ port9 ] = -31;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 4500  Sensors: no change  IMEs: no change
		motor[ port2 ] = -117;
		motor[ port3 ] = -117;
		motor[ port6 ] = 0;
		motor[ port7 ] = 0;
		motor[ port8 ] = -123;
		motor[ port9 ] = -123;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 4650  Sensors: no change  IMEs: no change
		motor[ port4 ] = 120;
		motor[ port5 ] = 120;
		wait1Msec( P_Freq * 3 );		// wait 450

		// 5100  Sensors: no change  IMEs: no change
		motor[ port2 ] = -91;
		motor[ port3 ] = -91;
		motor[ port8 ] = -77;
		motor[ port9 ] = -77;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 5250  Sensors: no change  IMEs: no change
		motor[ port2 ] = 1;
		motor[ port3 ] = 1;
		motor[ port4 ] = 0;
		motor[ port5 ] = 0;
		motor[ port8 ] = 1;
		motor[ port9 ] = 1;
		wait1Msec( P_Freq * 2 );		// wait 300

		// 5550  Sensors: no change  IMEs: no change
		motor[ port1 ] = 12;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 5700  Sensors: no change  IMEs: no change
		motor[ port2 ] = -4;
		motor[ port3 ] = -4;
		wait1Msec( P_Freq * 2 );		// wait 300

		// 6000  Sensors: no change  IMEs: no change
		motor[ port2 ] = -97;
		motor[ port3 ] = -97;
		motor[ port8 ] = 82;
		motor[ port9 ] = 82;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 6150  Sensors: no change  IMEs: no change
		motor[ port2 ] = -122;
		motor[ port3 ] = -122;
		motor[ port8 ] = 127;
		motor[ port9 ] = 127;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 6300  Sensors: no change  IMEs: no change
		motor[ port2 ] = -115;
		motor[ port3 ] = -115;
		motor[ port4 ] = -120;
		motor[ port5 ] = -120;
		wait1Msec( P_Freq * 3 );		// wait 450

		// 6750  Sensors: no change  IMEs: no change
		motor[ port4 ] = 0;
		motor[ port5 ] = 0;
		motor[ port8 ] = 113;
		motor[ port9 ] = 113;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 6900  Sensors: no change  IMEs: no change
		motor[ port2 ] = 1;
		motor[ port3 ] = 1;
		motor[ port8 ] = 1;
		motor[ port9 ] = 1;
		wait1Msec( P_Freq * 2 );		// wait 300

		// 7200  Sensors: no change  IMEs: no change
		motor[ port2 ] = -4;
		motor[ port3 ] = -4;
		motor[ port8 ] = 36;
		motor[ port9 ] = 36;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 7350  Sensors: no change  IMEs: no change
		motor[ port2 ] = -29;
		motor[ port3 ] = -29;
		motor[ port8 ] = 101;
		motor[ port9 ] = 101;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 7500  Sensors: no change  IMEs: no change
		motor[ port2 ] = -25;
		motor[ port3 ] = -25;
		motor[ port8 ] = 1;
		motor[ port9 ] = 1;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 7650  Sensors: no change  IMEs: no change
		motor[ port2 ] = 66;
		motor[ port3 ] = 66;
		motor[ port8 ] = 9;
		motor[ port9 ] = 9;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 7800  Sensors: no change  IMEs: no change
		motor[ port2 ] = 127;
		motor[ port3 ] = 127;
		motor[ port8 ] = 59;
		motor[ port9 ] = 59;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 7950  Sensors: no change  IMEs: no change
		motor[ port8 ] = 64;
		motor[ port9 ] = 64;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 8100  Sensors: no change  IMEs: no change
		motor[ port8 ] = 83;
		motor[ port9 ] = 83;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 8250  Sensors: no change  IMEs: no change
		motor[ port2 ] = 99;
		motor[ port3 ] = 99;
		motor[ port8 ] = 68;
		motor[ port9 ] = 68;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 8400  Sensors: no change  IMEs: no change
		motor[ port2 ] = 46;
		motor[ port3 ] = 46;
		motor[ port8 ] = 11;
		motor[ port9 ] = 11;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 8550  Sensors: no change  IMEs: no change
		motor[ port2 ] = 9;
		motor[ port3 ] = 9;
		motor[ port8 ] = 7;
		motor[ port9 ] = 7;
		wait1Msec( P_Freq * 2 );		// wait 300

		// 8850  Sensors: no change  IMEs: no change
		motor[ port2 ] = 35;
		motor[ port3 ] = 35;
		motor[ port8 ] = 1;
		motor[ port9 ] = 1;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 9000  Sensors: no change  IMEs: no change
		motor[ port8 ] = -20;
		motor[ port9 ] = -20;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 9150  Sensors: no change  IMEs: no change
		motor[ port8 ] = -12;
		motor[ port9 ] = -12;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 9300  Sensors: no change  IMEs: no change
		motor[ port2 ] = 125;
		motor[ port3 ] = 125;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 9450  Sensors: no change  IMEs: no change
		motor[ port8 ] = -19;
		motor[ port9 ] = -19;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 9600  Sensors: no change  IMEs: no change
		motor[ port8 ] = -13;
		motor[ port9 ] = -13;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 9750  Sensors: no change  IMEs: no change
		motor[ port2 ] = 18;
		motor[ port3 ] = 18;
		motor[ port8 ] = -5;
		motor[ port9 ] = -5;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 9900  Sensors: no change  IMEs: no change
		motor[ port2 ] = 1;
		motor[ port3 ] = 1;
		wait1Msec( P_Freq * 2 );		// wait 300

		// 10200  Sensors: no change  IMEs: no change
		motor[ port6 ] = 127;
		motor[ port7 ] = 127;
		motor[ port8 ] = 1;
		motor[ port9 ] = 1;
		wait1Msec( P_Freq * 3 );		// wait 450

		// 10650  Sensors: no change  IMEs: no change
		motor[ port6 ] = 0;
		motor[ port7 ] = 0;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 10800  Sensors: no change  IMEs: no change
		motor[ port2 ] = -12;
		motor[ port3 ] = -12;
		motor[ port8 ] = -5;
		motor[ port9 ] = -5;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 10950  Sensors: no change  IMEs: no change
		motor[ port2 ] = -54;
		motor[ port3 ] = -54;
		motor[ port8 ] = -42;
		motor[ port9 ] = -42;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 11100  Sensors: no change  IMEs: no change
		motor[ port2 ] = -104;
		motor[ port3 ] = -104;
		motor[ port8 ] = -74;
		motor[ port9 ] = -74;
		wait1Msec( P_Freq * 2 );		// wait 300

		// 11400  Sensors: no change  IMEs: no change
		motor[ port2 ] = 1;
		motor[ port3 ] = 1;
		motor[ port8 ] = 1;
		motor[ port9 ] = 1;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 11550  Sensors: no change  IMEs: no change
		motor[ port2 ] = 7;
		motor[ port3 ] = 7;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 11700  Sensors: no change  IMEs: no change
		motor[ port6 ] = -127;
		motor[ port7 ] = -127;
		wait1Msec( P_Freq * 1 );		// wait 150

		// 11850  Sensors: no change  IMEs: no change
		motor[ port2 ] = 1;
		motor[ port3 ] = 1;
		wait1Msec( P_Freq * 2 );		// wait 300

		// 12150  Sensors: no change  IMEs: no change
		motor[ port6 ] = 0;
		motor[ port7 ] = 0;


}
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		//*============= MAIN CONTROLER =================

		//code for chassis
		motor[LF] = vexRT[Ch3];
		motor[LB] = vexRT[Ch3];
		motor[RF] = vexRT[Ch2];
		motor[RB] = vexRT[Ch2];

		//code for mobile lift
		if (vexRT[Btn5U])
		{
			motor[MLift] = -Lift;
			motor[MLift2] = -Lift;
		}
		else if (vexRT[Btn5D])
		{
			motor[MLift] = Lift;
			motor[MLift2] = Lift;
		}
		else
		{
			motor[MLift] = 0;
			motor[MLift2] = 0;
		}
		//*============= PARTNER CONTROLER ==============

		//code for arm
		if (vexRT[Btn6UXmtr2])
		{
			motor[Arm] = RoArm;
			motor[Arm2] = RoArm;
		}
		else if (vexRT[Btn5UXmtr2])
		{
			motor[Arm] = -RoArm/1.5;
			motor[Arm2] = -RoArm/1.5;
		}
		else if (vexRT[Btn6DXmtr2])
		{
			motor[Arm] = RoArm/2.5;
			motor[Arm2] = RoArm/2.5;
		}
		else
		{
			motor[Arm] = 0;
			motor[Arm2] = 0;
		}

		//code for claw

		if (vexRT[Btn8RXmtr2])
		{
			motor[Claw] = RoClaw;
		}
		else if (vexRT[Btn8DXmtr2])
		{
			motor[Claw] = -RoClaw;
		}
		else
		{
			motor[Claw] = -12;
		}

	}
}
