#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  imeL,           sensorNone)
#pragma config(Sensor, dgtl2,  imeR,           sensorNone)
#pragma config(Sensor, I2C_1,  RBEn,           sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  LBEn,           sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           Claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RF,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RB,            tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port4,           Arm,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Arm2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           MLift2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           MLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LF,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LB,            tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//!!Code automatically generated by 'ROBOTC' configuration wizard               !!//
//!!Code automatically generated by 'ROBOTC' configuration wizard               !!//

//motor speed for mobile lift
int R_Freq = 150;
int Lift = 127;
//motor speed for Arm
int RoArm = 80;
//motor speed for claw
int RoClaw = 120;
int R_Batt = 7919;
int P_Freq = R_Freq * (R_Batt / nImmediateBatteryLevel);
// Initial values for Sensors:
// Initial values for IMEs: port 3 = 0  port 9 = 0

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	motor[RF] = 0;
	motor[RB] = 0;
	motor[LB] = 0;
	motor[LF] = 0;
	wait10Msec(100);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
//*============= MAIN CONTROLER =================

        //code for chassis
        motor[LF] = vexRT[Ch3];
        motor[LB] = vexRT[Ch3];
        motor[RF] = vexRT[Ch2];
        motor[RB] = vexRT[Ch2];

        //code for mobile lift
        if (vexRT[Btn5U])
        {
          motor[MLift] = -Lift;
          motor[MLift2] = -Lift;
        }
        else if (vexRT[Btn5D])
        {
          motor[MLift] = Lift;
          motor[MLift2] = Lift;
        }
        else
        {
          motor[MLift] = 0;
          motor[MLift2] = 0;
        }
//*============= PARTNER CONTROLER ==============

        //code for arm
        if (vexRT[Btn6UXmtr2])
        {
            motor[Arm] = RoArm;
            motor[Arm2] = RoArm;
        }
        else if (vexRT[Btn5UXmtr2])
        {
            motor[Arm] = -RoArm/1.5;
            motor[Arm2] = -RoArm/1.5;
        }
        else if (vexRT[Btn6DXmtr2])
        {
        	motor[Arm] = RoArm/2.5;
        	motor[Arm2] = RoArm/2.5;
        }
        else
        {
            motor[Arm] = 0;
            motor[Arm2] = 0;
        }

        //code for claw

        if (vexRT[Btn8RXmtr2])
        {
            motor[Claw] = RoClaw;
        }
        else if (vexRT[Btn8DXmtr2])
        {
            motor[Claw] = -RoClaw;
        }
        else
        {
        	motor[Claw] = -12;
        }

  }
}
