
#pragma config(Sensor, dgtl1,  imeL,           sensorNone)
#pragma config(Sensor, dgtl2,  imeR,           sensorNone)
#pragma config(Sensor, I2C_1,  RBEn,           sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  LBEn,           sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           Claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RF,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RB,            tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port4,           Arm,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Arm2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           MLift2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           MLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LF,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LB,            tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//!!Code automatically generated by 'ROBOTC' configuration wizard               !!//
//!!Code automatically generated by 'ROBOTC' configuration wizard               !!//


int R_Freq = 100;
int R_Batt = 7978;
int P_Freq = R_Freq * (R_Batt / nImmediateBatteryLevel);
// Initial values for Sensors:
// Initial values for IMEs: port 3 = 0  port 9 = 0
task main()
{
wait1Msec( P_Freq * 1 );		// wait 100

// 100  Sensors: no change  IMEs: no change
motor[ port1 ] = 120;
motor[ port2 ] = 9;
motor[ port3 ] = 9;
motor[ port4 ] = -120;
motor[ port5 ] = -120;
wait1Msec( P_Freq * 5 );		// wait 500

// 600  Sensors: no change  IMEs: no change
motor[ port4 ] = 0;
motor[ port5 ] = 0;
wait1Msec( P_Freq * 6 );		// wait 600

// 1200  Sensors: no change  IMEs: no change
motor[ port6 ] = 127;
motor[ port7 ] = 127;
wait1Msec( P_Freq * 7 );		// wait 700

// 1900  Sensors: no change  IMEs: no change
motor[ port6 ] = 0;
motor[ port7 ] = 0;
wait1Msec( P_Freq * 1 );		// wait 100

// 2000  Sensors: no change  IMEs: no change
motor[ port2 ] = 97;
motor[ port3 ] = 97;
wait1Msec( P_Freq * 1 );		// wait 100

// 2100  Sensors: no change  IMEs: no change
motor[ port2 ] = 127;
motor[ port3 ] = 127;
motor[ port8 ] = 64;
motor[ port9 ] = 64;
wait1Msec( P_Freq * 22 );		// wait 2300

// 4400  Sensors: no change  IMEs: no change
motor[ port2 ] = 89;
motor[ port3 ] = 89;
motor[ port8 ] = -29;
motor[ port9 ] = -29;
wait1Msec( P_Freq * 1 );		// wait 100

// 4500  Sensors: no change  IMEs: no change
motor[ port2 ] = 7;
motor[ port3 ] = 7;
motor[ port8 ] = 1;
motor[ port9 ] = 1;
wait1Msec( P_Freq * 4 );		// wait 400

// 4900  Sensors: no change  IMEs: no change
motor[ port6 ] = -127;
motor[ port7 ] = -127;
wait1Msec( P_Freq * 9 );		// wait 900

// 5800  Sensors: no change  IMEs: no change
motor[ port6 ] = 0;
motor[ port7 ] = 0;
wait1Msec( P_Freq * 4 );		// wait 400

// 6200  Sensors: no change  IMEs: no change
motor[ port4 ] = 120;
motor[ port5 ] = 120;
wait1Msec( P_Freq * 6 );		// wait 400

// 6600  Sensors: no change  IMEs: no change
motor[ port4 ] = 0;
motor[ port5 ] = 0;
wait1Msec( P_Freq * 13 );		// wait 1300

// 7900  Sensors: no change  IMEs: no change
motor[ port1 ] = 12;
wait1Msec( P_Freq * 3 );		// wait 300

// 8200  Sensors: no change  IMEs: no change
motor[ port1 ] = -120;
wait1Msec( P_Freq * 3 );		// wait 300

// 8500  Sensors: no change  IMEs: no change
motor[ port1 ] = 12;
wait1Msec( P_Freq * 2 );		// wait 200

// 8700  Sensors: no change  IMEs: no change
motor[ port4 ] = -120;
motor[ port5 ] = -120;
wait1Msec( P_Freq * 2 );		// wait 200

// 8900  Sensors: no change  IMEs: no change
motor[ port4 ] = 0;
motor[ port5 ] = 0;
wait1Msec( P_Freq * 9 );		// wait 900

// 9800  Sensors: no change  IMEs: no change
motor[ port4 ] = -120;
motor[ port5 ] = -120;
wait1Msec( P_Freq * 4 );		// wait 400

// 10200  Sensors: no change  IMEs: no change
motor[ port4 ] = 0;
motor[ port5 ] = 0;
wait1Msec( P_Freq * 8 );		// wait 800

// 11000  Sensors: no change  IMEs: no change
motor[ port8 ] = 19;
motor[ port9 ] = 19;
wait1Msec( P_Freq * 1 );		// wait 100

// 11100  Sensors: no change  IMEs: no change
motor[ port8 ] = 6;
motor[ port9 ] = 6;
wait1Msec( P_Freq * 1 );		// wait 100

// 11200  Sensors: no change  IMEs: no change
motor[ port2 ] = 1;
motor[ port3 ] = 1;
motor[ port8 ] = 1;
motor[ port9 ] = 1;
wait1Msec( P_Freq * 1 );		// wait 100

// 11300  Sensors: no change  IMEs: no change
motor[ port2 ] = -8;
motor[ port3 ] = -8;
motor[ port8 ] = -45;
motor[ port9 ] = -45;
wait1Msec( P_Freq * 1 );		// wait 100

// 11400  Sensors: no change  IMEs: no change
motor[ port2 ] = -124;
motor[ port3 ] = -124;
motor[ port8 ] = -125;
motor[ port9 ] = -125;
wait1Msec( P_Freq * 4 );		// wait 400

// 11800  Sensors: no change  IMEs: no change
motor[ port2 ] = -127;
motor[ port3 ] = -127;
wait1Msec( P_Freq * 13 );		// wait 1300

// 13100  Sensors: no change  IMEs: no change
motor[ port8 ] = 21;
motor[ port9 ] = 21;
wait1Msec( P_Freq * 1 );		// wait 100

// 13200  Sensors: no change  IMEs: no change
motor[ port8 ] = 120;
motor[ port9 ] = 120;
wait1Msec( P_Freq * 4 );		// wait 400

// 13600  Sensors: no change  IMEs: no change
motor[ port8 ] = 124;
motor[ port9 ] = 124;
wait1Msec( P_Freq * 5 );		// wait 500

// 14100  Sensors: no change  IMEs: no change
motor[ port8 ] = 116;
motor[ port9 ] = 116;
wait1Msec( P_Freq * 1 );		// wait 100

// 14200  Sensors: no change  IMEs: no change
motor[ port2 ] = -21;
motor[ port3 ] = -21;
motor[ port8 ] = 1;
motor[ port9 ] = 1;
wait1Msec( P_Freq * 1 );		// wait 100

// 14300  Sensors: no change  IMEs: no change
motor[ port2 ] = 1;
motor[ port3 ] = 1;
wait1Msec( P_Freq * 1 );		// wait 100

// 14400  Sensors: no change  IMEs: no change
motor[ port8 ] = 29;
motor[ port9 ] = 29;
wait1Msec( P_Freq * 1 );		// wait 100

// 14500  Sensors: no change  IMEs: no change
motor[ port8 ] = 1;
motor[ port9 ] = 1;
wait1Msec( P_Freq * 1 );		// wait 100

// 14600  Sensors: no change  IMEs: no change
motor[ port2 ] = -42;
motor[ port3 ] = -42;
wait1Msec( P_Freq * 1 );		// wait 100

// 14700  Sensors: no change  IMEs: no change
motor[ port2 ] = -127;
motor[ port3 ] = -127;
motor[ port8 ] = 127;
motor[ port9 ] = 127;
wait1Msec( P_Freq * 1 );		// wait 100

// 14800  Sensors: no change  IMEs: no change
motor[ port2 ] = 8;
motor[ port3 ] = 8;
motor[ port8 ] = -5;
motor[ port9 ] = -5;
wait1Msec( P_Freq * 1 );		// wait 100

// 14900  Sensors: no change  IMEs: no change
motor[ port8 ] = 1;
motor[ port9 ] = 1;
wait1Msec( P_Freq * 1 );		// wait 100

// 15000  Sensors: no change  IMEs: no change
motor[ port2 ] = 127;
motor[ port3 ] = 127;
motor[ port8 ] = 127;
motor[ port9 ] = 127;
wait1Msec( P_Freq * 9 );		// wait 900

// 15900  Sensors: no change  IMEs: no change
motor[ port2 ] = 80;
motor[ port3 ] = 80;
wait1Msec( P_Freq * 1 );		// wait 100

// 16000  Sensors: no change  IMEs: no change
motor[ port2 ] = 40;
motor[ port3 ] = 40;
wait1Msec( P_Freq * 1 );		// wait 100

// 16100  Sensors: no change  IMEs: no change
motor[ port2 ] = 112;
motor[ port3 ] = 112;
wait1Msec( P_Freq * 1 );		// wait 100

// 16200  Sensors: no change  IMEs: no change
motor[ port2 ] = 127;
motor[ port3 ] = 127;
wait1Msec( P_Freq * 3 );		// wait 300

// 16500  Sensors: no change  IMEs: no change
motor[ port2 ] = 98;
motor[ port3 ] = 98;
motor[ port8 ] = 124;
motor[ port9 ] = 124;
wait1Msec( P_Freq * 1 );		// wait 100

// 16600  Sensors: no change  IMEs: no change
motor[ port2 ] = 1;
motor[ port3 ] = 1;
motor[ port8 ] = 1;
motor[ port9 ] = 1;
wait1Msec( P_Freq * 5 );		// wait 500

// 17100  Sensors: no change  IMEs: no change
motor[ port2 ] = 28;
motor[ port3 ] = 28;
motor[ port8 ] = 59;
motor[ port9 ] = 59;
wait1Msec( P_Freq * 1 );		// wait 100

// 17200  Sensors: no change  IMEs: no change
motor[ port2 ] = 127;
motor[ port3 ] = 127;
motor[ port8 ] = 127;
motor[ port9 ] = 127;
wait1Msec( P_Freq * 1 );		// wait 100

// 17300  Sensors: no change  IMEs: no change
motor[ port6 ] = 127;
motor[ port7 ] = 127;
wait1Msec( P_Freq * 1 );		// wait 100

// 17400  Sensors: no change  IMEs: no change
motor[ port2 ] = 1;
motor[ port3 ] = 1;
motor[ port8 ] = 100;
motor[ port9 ] = 100;
wait1Msec( P_Freq * 1 );		// wait 100

// 17500  Sensors: no change  IMEs: no change
motor[ port8 ] = 1;
motor[ port9 ] = 1;
wait1Msec( P_Freq * 4 );		// wait 400

// 17900  Sensors: no change  IMEs: no change
motor[ port6 ] = 0;
motor[ port7 ] = 0;
wait1Msec( P_Freq * 3 );		// wait 300

// 18200  Sensors: no change  IMEs: no change
motor[ port8 ] = 18;
motor[ port9 ] = 18;
wait1Msec( P_Freq * 1 );		// wait 100

// 18300  Sensors: no change  IMEs: no change
motor[ port2 ] = 127;
motor[ port3 ] = 127;
motor[ port8 ] = 127;
motor[ port9 ] = 127;
wait1Msec( P_Freq * 6 );		// wait 600

// 18900  Sensors: no change  IMEs: no change
motor[ port2 ] = 1;
motor[ port3 ] = 1;
motor[ port8 ] = 1;
motor[ port9 ] = 1;
wait1Msec( P_Freq * 6 );		// wait 600

// 19500  Sensors: no change  IMEs: no change
motor[ port8 ] = -25;
motor[ port9 ] = -25;
wait1Msec( P_Freq * 1 );		// wait 100

// 19600  Sensors: no change  IMEs: no change
motor[ port2 ] = -127;
motor[ port3 ] = -127;
motor[ port8 ] = -127;
motor[ port9 ] = -127;
wait1Msec( P_Freq * 12 );		// wait 1200

// 20800  Sensors no change  IMEs: no change
motor[ port2 ] = 11;
motor[ port3 ] = 11;
motor[ port8 ] = 21;
motor[ port9 ] = 21;
wait1Msec( P_Freq * 1 );		// wait 100

// 20900  Sensors: no change  IMEs: no change
motor[ port8 ] = 1;
motor[ port9 ] = 1;
wait1Msec( P_Freq * 7 );		// wait 700

// 21600  Sensors: no change  IMEs: no change
motor[ port6 ] = -127;
motor[ port7 ] = -127;
wait1Msec ( P_Freq * 2.5 );



}
