#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  imeL,           sensorNone)
#pragma config(Sensor, dgtl2,  imeR,           sensorNone)
#pragma config(Sensor, I2C_1,  RBEn,           sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  LBEn,           sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           Claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RF,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RB,            tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port4,           Arm,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Arm2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           MLift2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           MLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LF,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LB,            tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//!!Code automatically generated by 'ROBOTC' configuration wizard               !!//
//!!Code automatically generated by 'ROBOTC' configuration wizard               !!//

//motor speed for mobile lift
int Lift = 127;
//motor speed for Arm
int RoArm = 80;
//motor speed for claw
int RoClaw = 120;

task main()
{
	motor[Claw] = 120;
	motor[RF] = 127;
	motor[RB] = 127;
	motor[LB] = 127;
	motor[LF] = 127;
	wait10Msec(2);

	motor[Claw] = 120;
	motor[Arm] = -120;
	motor[Arm2] = -120;
	wait10Msec(1);

	motor[Claw] = 120;
	motor[MLift] = 127;
	motor[MLift2] = 127;
	wait10Msec(1);

	motor[Claw] = 120;
	motor[RF] = 127;
	motor[RB] = 127;
	motor[LB] = 127;
	motor[LF] = 127;
	wait10Msec(1);

	motor[Claw] = 120;
	motor[RF] = 127;
	motor[RB] = 127;
	motor[LB] = 127;
	motor[LF] = 127;
	wait10Msec(1);


	motor[Claw] = 120;
	motor[MLift] = -127;
	motor[MLift2] = -127;
	wait10Msec(1);

	motor[Arm] = 120;
	motor[Arm2] = 120;
	motor[RF] = -127;
	motor[RB] = -127;
	motor[LB] = -127;
	motor[LF] = -127;
	wait10Msec(2);

	motor[Claw] = -120
	motor[RF] = 127;
	motor[RB] = 127;
	motor[LB] = -127;
	motor[LF] = -127;
	wait10Msec(1);

	motor[A
	motor[RF] = 127;
	motor[RB] = 127;
	motor[LB] = 127;
	motor[LF] = 127;
	wait10Msec(2);

	motor[MLift] = 127;
	motor[MLift2] = 127;
	wait10Msec(1);

	motor[RF] = -127;
	motor[RB] = -127;
	motor[LB] = -127;
	motor[LF] = -127;
	wait10Msec(0.5);

	motor[MLift] = -127;
	motor[MLift2] = -127;
	wait10Msec(1);

	motor[RF] = -127;
	motor[RB] = -127;
	motor[LB] = -127;
	motor[LF] = -127;
	wait10Msec(1);




}
