#pragma config(Sensor, in5,    C_POT,          sensorPotentiometer)
#pragma config(Sensor, in4,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl7,  LIFT,           sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  RIGHT_DRIVE_ENC, sensorQuadEncoder)
#pragma config(Sensor, dgtl11, LEFT_DRIVE_ENC, sensorQuadEncoder)
#pragma config(Motor,  port1,           MOBILE_GOAL_INTAKE, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Chainbar,      tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           RIGHT_DRIVE_F, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           RIGHT_DRIVE_B, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           RIGHT_LIFT_BOTTOM, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           LEFT_LIFT_BOTTOM, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           RIGHT_LIFT_TOP,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           LEFT_LIFT_TOP,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           LEFT_DRIVE,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          ROLLERS,       tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "Subsystems/chainBar.c"
//#include "control_functions.c"

void _chassis(int leftDrive, int rightDrive){
	if(vexRT[Btn6U] == true){
		motor[RIGHT_DRIVE_B] = -leftDrive;
		motor[RIGHT_DRIVE_F] = -leftDrive;
		motor[LEFT_DRIVE] = -rightDrive;
		//motor[LEFT_DRIVE_F] = -rightDrive;
	}else if(vexRT[Btn6D] == true){
		motor[RIGHT_DRIVE_F] = 25;
		motor[RIGHT_DRIVE_B] = -25;
		motor[LEFT_DRIVE] = 25;
		//motor[LEFT_DRIVE_B] = -25;
	}else{
		motor[RIGHT_DRIVE_B] = rightDrive;
		motor[RIGHT_DRIVE_F] = rightDrive;
		motor[LEFT_DRIVE] = leftDrive;
		//motor[LEFT_DRIVE_F] = leftDrive;
	}
}
void _chainbar(int speed){
	motor[Chainbar] = speed;
}
void _mobileGoal(int speed){
	motor[MOBILE_GOAL_INTAKE] = speed;
}
void _lift(int speed){
	motor[RIGHT_LIFT_BOTTOM] = -speed;
	motor[LEFT_LIFT_BOTTOM] = -speed;
	motor[Lift] = -speed;
}
void _intake(int speed){
	motor[ROLLERS] = -speed;
}
bool up = false;
task main(){
	//startTask(chainBar_PID);
	//int chainBar_lastPoint;

	bLCDBacklight = true;
	string mainBattery;
	displayLCDCenteredString(0,"Welcome 356B");
	wait1Msec(1000);
	clearLCDLine(0);
	while(1){
		int leftPower = -vexRT(Ch3);
		int rightPower = -vexRT(Ch2);

		_chassis(leftPower, rightPower);

		if(vexRT[Btn5UXmtr2] == 1){
			_chainbar(120);
		}else if(vexRT[Btn5DXmtr2] == 1){
			//while(SensorValue[ultra] < 1){
				_chainbar(-120);
			//}
			//_chainbar(-50);
		}else{
			_chainbar(-15);
		}

		if(vexRT[Btn7UXmtr2] == 1){
			_mobileGoal(127);
		}else if(vexRT[Btn7DXmtr2] == 1){
			_mobileGoal(-127);
		}else{
			_mobileGoal(0);
		}

		if(vexRT[Btn6UXmtr2] == 1){
			_lift(-127);
			up = true;
		}else if(vexRT[Btn6DXmtr2] == 1){
			_lift(105);
			up = false;
		}else{
			if(up == false)
				_lift(15);
			else
				_lift(-10);
		}

		if(vexRT[Btn8UXmtr2] == 1){
			_intake(127);
		}else if(vexRT[Btn8DXmtr2] == 1){
			_intake(-127);
		}else{
			_intake(40);
		}

		//clearLCDLine(0);
		//clearLCDLine(1);

		//displayLCDString(0, 0, "Primary: ");
		//sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V');
		//displayNextLCDString(mainBattery);

		//displayLCDString(1, 0, "Backup: ");
		//sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');
		//displayNextLCDString(backupBattery);

		delay(10);
	}
}
