#pragma config(Sensor, in1,    claw_bar_pot,   sensorPotentiometer)
#pragma config(Sensor, in2,    right_mogo_pot, sensorPotentiometer)
#pragma config(Sensor, in3,    gyroscope,      sensorGyro)
#pragma config(Sensor, dgtl7,  dblift_encoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  right_chassis_encoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl11, left_chassis_encoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           right_mobile_goal, tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           right_drive_front, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           right_drive_rear, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           claw_,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           left_lift,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           right_lift,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           claw_bar,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           left_drive_front, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           left_drive_rear, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          left_mobile_goal, tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#define right_enc SensorValue[right_chassis_encoder]
#define left_enc SensorValue[left_chassis_encoder]
#define mogo_rpot SensorValue[right_mogo_pot]
#define mogo_lpot SensorValue[left_mogo_pot]
#define gyro SensorValue[gyroscope]
#define claw_bar_pot SensorValue[claw_bar_sensor]
#define lift_sensor SensorValue[dblift_pot]
/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void left_drive(int speed){
	motor[left_drive_front] = speed;
	motor[left_drive_rear] = speed;
}
void right_drive(int speed){
	motor[right_drive_front] = speed;
	motor[right_drive_rear] = speed;
}
void drive_chassis(int speed){
	left_drive(speed);
	right_drive(speed);
}
void lift(int speed){
	motor[right_lift] = -speed;
	motor[left_lift] = -speed;
}
void claw_lift(int speed){
	motor[claw_bar] = speed;
}
void claw(int speed){
	motor[claw_] = speed;
}
void mogo(int speed){
	motor[right_mobile_goal] = speed;
	motor[left_mobile_goal] = speed;
}
int preset=0;





void mobile_goal_intake(int speed){
	motor[right_mobile_goal] = speed;
	motor[left_mobile_goal] = speed;
}

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

void mogo_speed(int speed){
	mobile_goal_intake(speed);
	wait1Msec(1000);
	mobile_goal_intake(0);
	wait1Msec(25);
}
void auto_drive(int distance, int speed){
	while(right_enc < distance){
		drive_chassis(speed);
	}
	drive_chassis(0);
	wait1Msec(25);
}

void drive_back(int distance, int speed){
	while(right_enc > distance){
		drive_chassis(-speed);
	}
	drive_chassis(0);
	wait1Msec(25);
}
void drive_chassis_init(){
	right_enc = 0;
	left_enc = 0;
}
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
bool finished = true;
void autonomous_1(){

claw(-100);
	lift(100);
	wait1Msec(500);
	claw(-15);
	lift(10);
	wait1Msec(25);

	mogo_speed(-100);

	auto_drive(1110, 120);
	wait1Msec(1000);
	mogo_speed(100);

	left_drive(-100);
	wait1Msec(250);
	left_drive(0);
	wait1Msec(25);

	wait1Msec(3000);
	drive_back(200, 120);



	right_drive(100);
	left_drive(-100);
	wait1Msec(750);
	right_drive(0);
	left_drive(0);
	wait1Msec(25);

	mogo_speed(-100);

	drive_chassis_init();

	drive_back(-200, 100);

	finished = false;
}
task autonomous()
{
  	drive_chassis_init(); //clear encoders
	clearTimer(T1);
	//while(finished){dd
		autonomous_1();
	//}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  while(true){
		if(vexRT[Btn6U]==true){
			motor[left_drive_front]= -vexRT[Ch2];
			motor[left_drive_rear]= -vexRT[Ch2];
			motor[right_drive_front]= -vexRT[Ch3];
			motor[right_drive_rear]= -vexRT[Ch3];
		}
		else{
			motor[left_drive_front]= vexRT[Ch3];
			motor[left_drive_rear]= vexRT[Ch3];
			motor[right_drive_front]= vexRT[Ch2];
			motor[right_drive_rear]= vexRT[Ch2];
		}
		if(vexRT[Btn6UXmtr2] == 1){
			lift(80);
		}else if(vexRT[Btn6DXmtr2] == 1){
			lift(-60);
		}else{
			lift(10);
		}

		if(vexRT[Btn5UXmtr2] == 1){
			claw_lift(120);
		}else if(vexRT[Btn5DXmtr2] == 1){
			claw_lift(-120);
		}else{
			claw_lift(12);
		}

		if(vexRT[Btn8UXmtr2] == 1){
			claw(120);
		}else if(vexRT[Btn8DXmtr2] == 1){
			claw(-120);
		}else{
			claw(-15);
		}

		if(vexRT[Btn7DXmtr2] == 1){
			mogo(120);
		}else if(vexRT[Btn7UXmtr2] == 1){
			mogo(-120);
		}else if(vexRT[Btn7LXmtr2] == 1){
			mogo(85);
		}else if(vexRT[Btn7RXmtr2] == 1){
			mogo(-85);
		}else{
			mogo(0);
		}

		delay(25);
	}
}
