#pragma config(Sensor, in1,    claw_bar_sensor,   sensorPotentiometer)
#pragma config(Sensor, in2,    right_mogo_pot, sensorPotentiometer)
#pragma config(Sensor, in3,    gyroscope,      sensorGyro)
#pragma config(Sensor, dgtl7,  dblift_encoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  right_chassis_encoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl11, left_chassis_encoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           right_mobile_goal, tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           claw_bar,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           right_lift,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           right_drive_rear, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           right_drive_front, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           left_drive_rear, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           left_drive_front, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           left_lift,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           claw_,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          left_mobile_goal, tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
#define right_enc SensorValue[right_chassis_encoder]
#define left_enc SensorValue[left_chassis_encoder]
#define mogo_rpot SensorValue[right_mogo_pot]
#define mogo_lpot SensorValue[left_mogo_pot]
#define gyro SensorValue[gyroscope]
#define claw_bar_pot SensorValue[claw_bar_sensor]
#define lift_sensor SensorValue[dblift_pot]

void left_drive(int speed){
	motor[left_drive_front] = speed;
	motor[left_drive_rear] = speed;
}
void right_drive(int speed){
	motor[right_drive_front] = speed;
	motor[right_drive_rear] = speed;
}
void drive_chassis(int speed){
	left_drive(speed);
	right_drive(speed);
}
void lift(int speed){
	motor[right_lift] = speed;
	motor[left_lift] = -speed;
}
void claw_lift(int speed){
	motor[claw_bar] = speed;
}
void claw(int speed){
	motor[claw_] = speed;
}
void mogo(int speed){
	motor[right_mobile_goal] = speed;
	motor[left_mobile_goal] = speed;
}

void preset(){
	if(SensorValue[claw_bar_sensor] > 2146 && vexRT[Btn8LXmtr2] == 1){
		while(SensorValue[claw_bar_sensor] > 2146){
			claw_lift(50);
		}
	}else if(SensorValue[claw_bar_sensor] < 2146 && vexRT[Btn8LXmtr2] == 1){
		while(SensorValue[claw_bar_sensor] < 2146){
			claw_lift(-50);
		}
	}else{
		claw_lift(0);
	}
	claw_lift(0);
	wait1Msec(25);
}

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

///*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
while(true){
		if(vexRT[Btn6U]==true){
			motor[left_drive_front]= vexRT[Ch2];
			motor[left_drive_rear]= vexRT[Ch2];
			motor[right_drive_front]= -vexRT[Ch3];
			motor[right_drive_rear]= -vexRT[Ch3];
		}
		else{
			motor[left_drive_front]= -vexRT[Ch3];
			motor[left_drive_rear]= -vexRT[Ch3];
			motor[right_drive_front]= vexRT[Ch2];
			motor[right_drive_rear]= vexRT[Ch2];
		}
		if(vexRT[Btn6UXmtr2] == 1){
			lift(110);
		}else if(vexRT[Btn6DXmtr2] == 1){
			lift(-50);
		}else{
			lift(10);
		}

		if(vexRT[Btn5UXmtr2] == 1){
			claw_lift(120);
		}else if(vexRT[Btn5DXmtr2] == 1){
			claw_lift(-120);
		}else{
			claw_lift(5);
		}

		if(vexRT[Btn8UXmtr2] == 1){
			claw(120);
		}else if(vexRT[Btn8DXmtr2] == 1){
			claw(-120);
		}else if(vexRT[Btn8LXmtr2] == 1){
			preset();
		}else{
			claw(0);
		}

		if(vexRT[Btn7DXmtr2] == 1){
			mogo(120);
		}else if(vexRT[Btn7UXmtr2] == 1){
			mogo(-120);
		}else if(vexRT[Btn7LXmtr2] == 1){
			mogo(85);
		}else if(vexRT[Btn7RXmtr2] == 1){
			mogo(-85);
		}else{
			mogo(0);
		}

		delay(25);
	}
}
