#pragma config(Sensor, in5,    C_POT,          sensorPotentiometer)
#pragma config(Sensor, in4,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl7,  LIFT,           sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  RIGHT_DRIVE_ENC, sensorQuadEncoder)
#pragma config(Sensor, dgtl11, LEFT_DRIVE_ENC, sensorQuadEncoder)
#pragma config(Motor,  port1,           MOBILE_GOAL_INTAKE, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Chainbar,      tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           RIGHT_DRIVE_F, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           RIGHT_DRIVE_B, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           RIGHT_LIFT_BOTTOM, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           LEFT_LIFT_BOTTOM, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           RIGHT_LIFT_TOP,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           LEFT_LIFT_TOP,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           LEFT_DRIVE,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          ROLLERS,       tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "driveTask.c"
#include "liftTask.c"
bool begin = false;
task start_(){
	_mogo(127);
	lift_Up(20, 100);
}
task intake_drop(){
	lift_Down(10, 60);
	chainbar_down(80);
	_mogo(100, -127);
	_intake(-100);
}


task main(){
	_liftClr();
	_driveClr();
	startTask(start_);
	_intake(30);
	_driveForward(1250, 100);
	_mogo(10);
	cal_gyro();
	//wait1Msec(400);
	//_driveForward(1250, 100);
	//_mogo(1500, -127);
	//chainbar_down(80);
	_mogo(900, -127);
	_mogo(-127);
	lift_Down(5, 100);
	_mogo(0);
	_intake(-127);
	wait1Msec(500);
	_lift(-50);
	_driveForward(1570, 100);
	stop_chassis();
	_intake(127);
	chainbar_down(120);
	_intake(30);
	lift_Up(10,100);
	chainbar_up(127);
	lift_Down(2, 100);
	_intake(-120);
	wait1Msec(200);

	_intake(127);
	lift_Up(7, 127);
	_driveForward(1810, 110);
	chainbar_down(127);
	lift_Down(2, 127);
	_intake(15);
	lift_Up(10, 127);
	chainbar_up(127);
	lift_Down(7, 127);
	_intake(-127);

	_driveBack(190, 240);
	turn(500, 120);
	_driveClr();
	_driveBack(-510, 120);
	turn(1400, 120);
	_driveClr();
	lift_Up(10, 100);
	_mogo(100);
	wait1Msec(300);
	_mogo(127);
	_driveForward(500, 70);
	_mogo(0);
	_mogo(500, -120);
	_driveBack(200, 120);
}
