#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    F_pot,          sensorPotentiometer)
#pragma config(Sensor, in3,    B_pot,          sensorPotentiometer)
#pragma config(Sensor, dgtl3,  rightDrive_enc, sensorQuadEncoder)
#pragma config(Sensor, dgtl1,  leftDrive_enc,  sensorQuadEncoder)
#pragma config(Motor,  port1,           left_1,        tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           right_3,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           left_2,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           right_2,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           left_3,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           B_mogo_r,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           B_mogo_l,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           F_mogo_r,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           F_mogo_l,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          right_1,       tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "chassis PID V1.c"

task main()
{
	while(1){
		if(vexRT[Btn6U]==true){
			right_chassis(-vexRT(Ch3));
			left_chassis(-vexRT(Ch2));
		}else{
			right_chassis(vexRT(Ch2));
			left_chassis(vexRT(Ch3));
		}

		if(vexRT[Btn5UXmtr2] == 1){
			B_mogo(-100);
		}else if(vexRT[Btn5DXmtr2] == 1){
			B_mogo(100);
		}else{
			B_mogo(0);
		}
		if(vexRT[Btn6UXmtr2] == 1){
			F_mogo(100);
		}else if(vexRT[Btn6DXmtr2] == 1){
			F_mogo(-100);
		}else{
			F_mogo(0);
		}
	}
}
