#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    F_pot,          sensorPotentiometer)
#pragma config(Sensor, in3,    B_pot,          sensorPotentiometer)
#pragma config(Sensor, dgtl3,  rightDrive_enc, sensorQuadEncoder)
#pragma config(Sensor, dgtl1,  leftDrive_enc,  sensorQuadEncoder)
#pragma config(Motor,  port1,           left_1,        tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           right_3,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           left_2,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           right_2,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           left_3,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           B_mogo_r,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           B_mogo_l,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           F_mogo_r,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           F_mogo_l,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          right_1,       tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/***************************
Nana Abekah
Team 356B
Start of project: 12/13/2017
***************************/



/***************************************************************************************************************
			Today is 12/13/2017. We started writing code for the skills robot. We are beginning with a PID controller.
			We are yet to tested this program. We also have to work on tuning the PID controller for forward and backward
			movements.

			Some few things to be completed:
			-Write PID for Gyro(priority)
			-LCD program selection code
			-Driver control program.
***************************************************************************************************************/
/***************************************************************************************************************
			Today is 12/20/2017. I finally got a chance to try out my PID program. There are a lot of bugs in the PID
			controller that needs to be fixed. So far the encoder PID works but there is work needed to be done on the gyro PID.
			The drive PID also needs to have controlled loops.

			Some few things to be completed:
			-Refine PID controllers(priority)
			-LCD program selection code
			-Driver control program(done).
***************************************************************************************************************/
/*********************************************************************************************************************
			Today is 12/29/2017. I refined the PID controllers for the gyro and encoders. I made the controls into functions
			instead of tasks. It's much easier to work with functions than tasks. So far, am happy with how the program
			is working. I may have to work on the derivative term of the controller. I also have to test the controller
			with 2 mobile goals on. Maybe I will have to tune it to calculate with extra weight on the robot. With 2 mobile
			goals, static friction changes and as a result, I may need to have 2 different PID constants for the encoders.

			Some few things to be completed:
			-LCD program selection code
**********************************************************************************************************************/

/*#include "library/pid_h.h"
#include "library/simplifications and variables.h"*/
#include "chassis PID V1.c" //include directory that contains functions


void display_PID_values(){
	clearLCDLine(0);
	clearLCDLine(1);
}

void _stopChassis(){
	right_chassis(5);
	left_chassis(5);
}
task main(){
	drive_chassis_init(); //reset chassis encoder values
			dgyro_chassis_init(); // calibrate gyro
	while(1){
		if(vexRT[Btn5D] == 1){
			drive_chassis_init(); //reset chassis encoder values
			dgyro_chassis_init(); // calibrate gyro

			_fMogo(-100); //bring the front mobile goal down
			roll_chassis(); //prevent chassis from drift
			//drivebase_PID(1232);					//move forward 4 tiles
			_driveForward(1240, 100);

			_fMogo(100);	//raise front mobile goal up.
			drivebase_PID(1000);
			//_drivegyro(1950, 100);
			_drivegyro(2200, 80);//170;
			drive_chassis_init();
			_driveForward(1390, 80);//-
			wait1Msec(500);
			_drivegyro(1300, 100);

			drive_chassis_init();
			_driveForward(700, 100);
			_fMogo(-100);
				drive_chassis(-65);
				wait1Msec(250);
				drive_chassis(0);
			_fMogo(100);
			drivebase_PID(280);
			_drivegyro(300, 100);
				drive_chassis(-65);
				wait1Msec(2000);
				drive_chassis(0);
			drive_chassis_init();
			dgyro_chassis_init();

			drivebase_PID(300);
			_drivegyro(-350, 50);
			_fMogo(-100);
			drive_chassis_init();
			_driveForward(770, 100);
			_fMogo(100);
			wait1Msec(500);
			_driveForward(800, 60);
			_drivegyro(-1510, 80);
			_bMogo(-100);
			backMogo(-50);
			drive_chassis_init();
			_driveBack(-750, -80);
			_bMogo(100);
			_drivegyro(-420, 100);
			drive_chassis_init();
			_driveBack(-900, -100);
			_bMogo(-100);
				drive_chassis(65);
				wait1Msec(300);
				drive_chassis(-5);
				drive_chassis(0);
			_bMogo(100);
			_drivegyro(-1610, 100);
			drive_chassis_init();
			_driveForward(200, 80);
			_drivegyro(-2500, 100);
			drive_chassis_init();
			_driveForward(120, 80);
			_fMogo(-100);
				drive_chassis(-65);
				wait1Msec(400);
				drive_chassis(5);
				drive_chassis(0);
			_fMogo(100);
			roll_chassis();
			dgyro_chassis_init();
			_drivegyro(-1250, 100);
				drive_chassis(-65);
				wait1Msec(2000);
				drive_chassis(0);




			// other side
			//reset before moving on

			drive_chassis_init();
			dgyro_chassis_init();
			drivebase_PID(570);
			_drivegyro(-580, 50);
			drive_chassis_init();
			_fMogo(-100);
			_driveForward(1500, 100);
			_fMogo(100);
				drive_chassis(85);
				wait1Msec(150);
				drive_chassis(-5);
				drive_chassis(0);
			//_drivegyro(-1300, 80);

			_drivegyro(-1400, 80);
			_bMogo(-100);
			drive_chassis_init();

			B_mogo(-20);
			_driveBack(-700, -80);
			_bMogo(100);
				drive_chassis(-70);
				wait1Msec(300);
				drive_chassis(-5);
				drive_chassis(0);
			_drivegyro(-2500, 80);
			drive_chassis_init();
			_driveBack(-1020, -80);
			_bMogo(-100);
				drive_chassis(70);
				wait1Msec(210);
				drive_chassis(-5);
				drive_chassis(0);
			_bMogo(100);
			_drivegyro(-1250, 80);
			drive_chassis_init();
			_driveForward(400, 60);
				drive_chassis(-5);
			_drivegyro(-530, 50);
			drive_chassis_init();
			_driveForward(700, 100);
			_fMogo(-100);
				drive_chassis(-65);
				wait1Msec(250);
				drive_chassis(0);
			_fMogo(100);
			_driveBack(280, -80);
			_drivegyro(-1670, 80);
				drive_chassis(-65);
				wait1Msec(2000);
				drive_chassis(5);
				drive_chassis(0);

			//last 10 points
			drive_chassis_init();
			dgyro_chassis_init();
				drive_chassis(60);
				wait1Msec(250);
				drive_chassis(0);
			_drivegyro(-1100, 80);
			_fMogo(-100);
			drive_chassis_init();
			_driveForward(1100, 100);
			_fMogo(100);
			drivebase_PID(800);
			_drivegyro(900, 100);
			drive_chassis_init();
			_driveForward(1400, 100);
			_drivegyro(1440, 80);
			drive_chassis_init();
			_driveForward(150, 80);
			_fMogo(-100);
				drive_chassis(-65);
				wait1Msec(250);
				drive_chassis(0);
			_fMogo(100);

			//done 80pts

			/*drive_chassis_init();
			_bMogo(-100);
			B_mogo(-5);
			drivebase_PID(-410);
			_bMogo(100);
			drive_chassis_init();
			drivebase_PID(400);
			_drivegyro(10, 80);
			drive_chassis_init();
			drivebase_PID(-730);
				right_chassis(-50);
				wait1Msec(700);
				right_chassis(0);
			_bMogo(-100);
				drive_chassis(-50);
				wait1Msec(700);
				drive_chassis(0);
			drive_chassis_init();
			drivebase_PID(-70);
			_bMogo(100);*/
		}
	}
//_drivegyro(1950, 80);
//_drivegyro(2100, 80);
//_drivegyro(1500, 80);
}
