#pragma config(Sensor, in8,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl9,  RIGHT_DRIVE_ENC, sensorQuadEncoder)
#pragma config(Sensor, dgtl11,  LEFT_DRIVE_ENC, sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  LIFT,           sensorQuadEncoder)
#pragma config(Motor,  port1,           MOBILE_GOAL_INTAKE, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port9,           Chainbar,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RIGHT_DRIVE_F, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           RIGHT_DRIVE_B, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           RIGHT_LIFT_BOTTOM,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LEFT_LIFT_BOTTOM,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LEFT_DRIVE_B,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           LEFT_DRIVE_F,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port2,           Lift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          ROLLERS,       tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "control_functions.c"



task main(){
	while(1){
		if(vexRT[Btn5D] == 1){
		_lift(700);
		_mobileGoal(127);
		_intake(30);
		_chainbar(-50);
		gyro_init();
		chassis_init();
		LIFT_ENC = 0;
		_chainbar(10);
		_lift(10);
		//_mobileGoal(50);

		Drive_enc(1210, 127);
		_mobileGoal(-100);
		wait1Msec(500);
		//_mobileGoal(0);

		Drive_enc(380, 127);
		_lift(-100);
		wait1Msec(500);
		_intake(-30);
		wait1Msec(300);
		_lift(100);
		_mobileGoal(0);
		_drivegyro(330, 120);
		_lift(15);
		chassis_init();
		Drive_enc(-400, 127);
		_drivegyro(1310, 120);
		chassis_init();
		_mobileGoal(80);
		Drive_enc(500, 127);
		wait1Msec(500);
		_mobileGoal(-100);
		Drive_enc(100, 127);
		_mobileGoal(0);
		}
	}
}
