#pragma config(Sensor, in6,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl9,  RIGHT_DRIVE_ENC, sensorQuadEncoder)
#pragma config(Sensor, dgtl11,  LEFT_DRIVE_ENC, sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  LIFT,           sensorQuadEncoder)
#pragma config(Motor,  port1,           MOBILE_GOAL_INTAKE, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port9,           Chainbar,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RIGHT_DRIVE_F, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           RIGHT_DRIVE_B, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           RIGHT_LIFT_BOTTOM,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LEFT_LIFT_BOTTOM,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LEFT_DRIVE_B,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           LEFT_DRIVE_F,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port2,           Lift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          ROLLERS,       tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "Subsystems/chainBar.c"
#include "control_functions.c"

/*void _chassis(int leftDrive, int rightDrive){
	if(vexRt[Btn6U] == true){
		motor[RIGHT_DRIVE_B] = -rightDrive;
		motor[RIGHT_DRIVE_F] = -rightDrive;
		motor[LEFT_DRIVE_B] = -leftDrive;
		motor[LEFT_DRIVE_F] = -leftDrive;
	}else{
		motor[RIGHT_DRIVE_B] = rightDrive;
		motor[RIGHT_DRIVE_F] = rightDrive;
		motor[LEFT_DRIVE_B] = leftDrive;
		motor[LEFT_DRIVE_F] = leftDrive;
	}
}

/*void _chainbar(int speed){
	motor[RIGHT_C_BAR] = speed;
	motor[LEFT_C_B] = speed;
}

void _mobileGoal(int speed){
	motor[MOBILE_GOAL_INTAKE] = speed;
}

void _lift(int speed){
	motor[RIGHT_LIFT] = -speed;
	motor[LEFT_LIFT] = -speed;
}

void _intake(int speed){
	motor[ROLLERS] = speed;
}*/
task main(){
	//startTask(chainBar_PID);
	//int chainBar_lastPoint;

	bLCDBacklight = true;
	string mainBattery, backupBattery;
	displayLCDCenteredString(0,"Welcome 356B");
	wait1Msec(1000);
	clearLCDLine(0);
	while(1){
		_chassis(-vexRT(Ch3), -vexRT(Ch2));

		if(vexRT[Btn5UXmtr2] == 1){
			_chainbar(-127);
		}else if(vexRT[Btn5DXmtr2] == 1){
			//while(SensorValue[ultra] < 1){
				_chainbar(127);
			//}
			//_chainbar(-50);
		}else{
			_chainbar(20);
		}

		if(vexRT[Btn7UXmtr2] == 1){
			_mobileGoal(127);
		}else if(vexRT[Btn7DXmtr2] == 1){
			_mobileGoal(-127);
		}else{
			_mobileGoal(0);
		}

		if(vexRT[Btn6UXmtr2] == 1){
			_lift(127);
		}else if(vexRT[Btn6DXmtr2] == 1){
			_lift(-127);
		}else{
			_lift(10);
		}

		if(vexRT[Btn8UXmtr2] == 1){
			_intake(127);
		}else if(vexRT[Btn8DXmtr2] == 1){
			_intake(-127);
		}else{
			_intake(30);
		}

		clearLCDLine(0);
		clearLCDLine(1);

		displayLCDString(0, 0, "Primary: ");
		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V');
		displayNextLCDString(mainBattery);

		displayLCDString(1, 0, "Backup: ");
		sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');
		displayNextLCDString(backupBattery);

		delay(25);
	}
}
