#pragma config(Sensor, in1,    C_POT,          sensorPotentiometer)
#pragma config(Motor,  port1,           MOBILE_GOAL_INTAKE, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RIGHT_C_BAR,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RIGHT_DRIVE_F, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           RIGHT_DRIVE_B, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           RIGHT_LIFT,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           LEFT_LIFT,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           LEFT_DRIVE_B,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           LEFT_DRIVE_F,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           LEFT_C_B,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          ROLLERS,       tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "pid_h.h"
#include "simpleSensors.h"

pid c_PID;
void c_PID_INIT(){
	c_PID.kP = 0.1;
	c_PID.kI = 0.1;
	c_PID.kD = 0.1;
}

void _chainbar(int speed){
	motor[RIGHT_C_BAR] = speed;
	motor[LEFT_C_B] = speed;
}

task chainBar_PID(){
	c_PID_INIT();
	while(true){
		c_PID.error = c_PID.target - chainBarPot;
		if(abs(c_PID.error) < 100)
			c_PID.integral = 1;
		else
			c_PID.integral = 0;

		if(c_PID.error == 0){	c_PID.integral = 0;	}

		c_PID.derivative = c_PID.error -c_PID.last_error;
		c_PID.last_error = c_PID.error;

		_chainbar((c_PID.error * c_PID.kP) + (c_PID.integral * c_PID.kI) + (c_PID.derivative* c_PID.kD));
	}
}
